# Generated by Django 4.0.1 on 2022-07-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Notification',
        ),
    ]
