# Generated by Django 4.1 on 2022-08-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_user_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.CharField(max_length=120),
        ),
    ]
