# Generated by Django 4.1 on 2022-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_podcast_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='picture',
            field=models.FileField(default='home/toralpal/public_html/media/images/logo.png', upload_to='home/toralpal/public_html/media/images/pdfHeaders'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='home/toralpal/public_html/media/images/logo.png', upload_to='home/toralpal/public_html/media/images/post_headings'),
        ),
    ]
