# Generated by Django 4.1 on 2023-02-13 12:37

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_title_color'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='post',
        #     name='content',
        #     field=tinymce.models.HTMLField(),
        # ),
    ]
