# Generated by Django 4.1 on 2023-02-13 13:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=tinymce.models.HTMLField(default='empty'),
            preserve_default=False,
        ),
    ]
